version: '2.0'
services:
  block-number-producer:
    image: 'ethereum-watch'
    entrypoint:
      - python
      - ./block_number_producer.py
  block-process-worker:
    image: 'ethereum-watch'
    entrypoint:
      - python
      - ./block_process_worker.py