version: '3.7'
services:
  block-number-producer:
    image: 'ethereum-watch'
    entrypoint:
      - python
      - ./block_number_producer.py
    restart:  always
  block-process-worker:
    image: 'ethereum-watch'
    entrypoint:
      - python
      - ./block_process_worker.py
    deploy:
      replicas: 3
    restart:  always